---
version: "3"
services:
  posterizarr:
    hostname: "posterizarr-dev"
    container_name: "posterizarr-dev"
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - -Mode
      - watch
    env_file:
      - .env.dev
    user: "1000:140"
    volumes:
      - "./config/posterizarr:/config:rw" # Map local config for easier access during dev
      - "./config/assets:/assets:rw"
      - "./config/posterizarr/manualassets:/manualassets:rw" # Map local manualassets
      - "./config/posterizarr/assetsbackup:/assetsbackup:rw" # Map local assetsbackup
    
  tautulli:
    hostname: tautulli-dev
    container_name: "tautulli-dev"
    image: "tautulli/tautulli"
    restart: "unless-stopped"
    entrypoint: 
      - "bin/sh -c"
    command:
      - "while true; do sleep 30; done"
    ports:
      - 8181:8181
    env_file:
      - .env.dev
    volumes:
      - "./config/posterizarr/watcher:/posterizarr/watcher:rw" # Map watcher dir
      - "./config/tautulli:/config:rw"
      - "./trigger.py:/scripts/trigger.py"

  kometa:
    hostname: kometa-dev
    container_name: "kometa-dev"
    image: kometateam/kometa:nightly
    restart: no
    command:
      "--libraries 'Movies' --run"
      #"--libraries "Movies|TV Shows|4k-Movies|4k-TV Shows" #optional
      #--run
    env_file:
      - .env.dev
    volumes:
      - "~/projects/kometa-config:/config:rw"
      - "./config/assets:/assets:rw"
  overlay-reset:
    image: kometateam/overlay-reset
    container_name: overlay-reset
    restart: no
    #command: --library Movies
    #command: --library "TV Shows"
    #command: --library 4k-Movies
    #command: --library "4k-TV Shows"
    env_file:
      - .env.dev
    environment:
      - TZ=TIMEZONE #optional
    volumes:
      - "./config/imagemaid:/config:rw"
