---
version: "3"
services:
  posterizarr:
    hostname: "posterizarr-dev"
    container_name: "posterizarr-dev"
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - -Mode
      - watch
    env_file:
      - .env.dev
    user: "1000:1001"
    volumes:
      - "./config:/config:rw" # Map local config for easier access during dev
      - "/assets:/assets:rw"
      - "./config/manualassets:/manualassets:rw" # Map local manualassets
      - "./config/assetsbackup:/assetsbackup:rw" # Map local assetsbackup
    
  tautulli:
    hostname: tautulli-dev
    container_name: "tautulli-dev"
    image: "tautulli/tautulli"
    restart: "unless-stopped"
    ports:
      - 8181:8181
    env_file:
      - .env.dev
    volumes:
      - "./config/watcher:/posterizarr/watcher:rw" # Map watcher dir
      - "./tautulli:/config:rw"
      - "./trigger.py:/scripts/trigger.py" 