---
version: "3"
services:
  posterizarr:
    hostname: "posterizarr"
    container_name: "posterizarr"
    env_file:
      - .env
    image: "ghcr.io/fscorrupt/docker-posterizarr:latest"
    restart: "unless-stopped"
    networks:
      - "proxy"
    volumes:
      - "/opt/appdata/posterizarr:/config:rw"
      - "/opt/appdata/kometa/assets:/assets:rw"
      - "/opt/appdata/posterizarr/assetsbackup:/assetsbackup:rw"
      - "/opt/appdata/posterizarr/manualassets:/manualassets:rw"
networks:
  proxy:
    driver: bridge
    external: true
